--- 
abstract: Postfix (MTA) server toolkit
author: 
  - Hans Dieter Pearcey <hdp@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.003
license: perl
name: POE-Component-Server-Postfix
requires: 
  MooseX::POE: 0
  POE::Filter::Postfix: 0
  POE::Wheel::SocketFactory: 0
  Test::More: 0
version: 0.001
